CREATE SEQUENCE SEQ_GAMES_2
    START WITH 1
    INCREMENT BY 1 NOCACHE
  NOCYCLE;

CREATE TABLE TBL_GAMES2
(
        GAME2_ID  INTERGER  DAFAULT SEQ_GAMES_2.NEXTVAL NOT NULL,
        TITLE   VARCHAR(100)  NOT NULL,
        VALUE   DECIMAL(10,2) NOT NULL,
        RELEASE_DATE  DATE    NOT NULL
);
